# Generated by Django 2.1.4 on 2018-12-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poss',
            old_name='aythor',
            new_name='author',
        ),
    ]
