# Generated by Django 2.1.4 on 2018-12-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181216_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poss',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='blog.Category', verbose_name='Categorias'),
        ),
    ]
